export const LOAD_EMPLOYEE_LIST_SUCCESS = 'LOAD_EMPLOYEE_LIST_SUCCESS';
export const CREATE_EMPLOYEE_SUCCESS = CREATE_EMPLOYEE_SUCCESS;
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';

export const LOAD_GRADE_SUCCESS = 'LOAD_GRADE_SUCCESS';
export const CREATE_GRADE_SUCCESS = 'CREATE_GRADE_SUCCESS';
export const EDIT_GRADE_SUCCESS = 'EDIT_GRADE_SUCCESS';

export const LOAD_EMPLOYMENT_SUCCESS = 'LOAD_EMPLOYMENT_SUCCESS';
export const CREATE_EMPLOYMENT_SUCCESS = 'CREATE_EMPLOYMENT_SUCCESS';
export const EDIT_EMPLOYMENT_SUCCESS = 'EDIT_EMPLOYMENT_SUCCESS';

export const LOAD_DEPENDENT_SUCCESS = 'LOAD_DEPENDENT_SUCCESS';
export const CREATE_DEPENDENT_SUCCESS = 'CREATE_DEPENDENT_SUCCESS';
export const EDIT_DEPENDENT_SUCCESS = 'EDIT_DEPENDENT_SUCCESS';

export const LOAD_ADDRESS_SUCCESS = 'LOAD_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';

export const LOAD_LOCATION_SUCCESS = 'LOAD_LOCATION_SUCCESS';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const EDIT_LOCATION_SUCCESS = 'EDIT_LOCATION_SUCCESS';
